"""Resolve bare `hash="HHHHHHHH"` references in `.binaryclass.xml` schemas
using the flat name list at `bin/generic_names.txt` (generated by
`build_generic_names.py`).

Two layers of resolution applied per pass:

  1. Standard Disrupt base-class header (6 hardcoded CRC32 -> name pairs)
     applied to ALL schemas. These don't appear in Generic XML so they
     need the hardcode fallback.
  2. CRC32(generic_name) and CRC32("text_" + generic_name) for every name
     in `generic_names.txt`. The text_X auto-derivation catches the
     paired-field naming convention.

By default scans every schema and overwrites in place. Edit TARGETS to
limit to specific schemas if needed.
"""
import re, zlib
from pathlib import Path

NAMES_TXT = Path(r"C:\Users\qstli\Downloads\WDL\disrupt-24-04-19\bin\generic_names.txt")
CLASSES = Path(r"C:\Users\qstli\Downloads\Gibbed.Disrupt-wasdennnoch\bin\projects\WDL\binary objects\classes")

# Limit to specific schemas (filenames without .binaryclass.xml). Empty = all.
TARGETS = []

# Standard Disrupt base class header — these don't appear in Generic XMLs
HEADER_NAMES = {
    "1FE8D41C": ("disNomadObjectId", "BinHex"),
    "61FC6B02": ("hidSingleObject", "Boolean"),
    "389F6DA7": ("hidKey", "BinHex"),
    "A788914C": ("hidValidationFailed", "Boolean"),
    "9D8873F8": ("text_hidName", "String"),
    "B9295CC7": ("hidName", "BinHex"),
}


def build_name_dict():
    d = {}
    names = [l.strip() for l in NAMES_TXT.read_text(encoding="utf-8").splitlines() if l.strip()]
    for n in names:
        d[f"{zlib.crc32(n.encode()) & 0xffffffff:08X}"] = n
    # text_X auto-derivations
    for n in names:
        t = f"text_{n}"
        d[f"{zlib.crc32(t.encode()) & 0xffffffff:08X}"] = t
    return d


name_dict = build_name_dict()
print(f"Built dict: {len(name_dict)} entries (CRC32 + text_X)")

# Header pass: <field hash="..." type="..."/> with canonical type
HEADER_RE = re.compile(r'<field hash="([0-9A-Fa-f]{8})" type="[^"]+"/>')
# General resolution: just replace the hash="..." attribute, keep type
HASH_RE = re.compile(r'hash="([0-9A-Fa-f]{8})"')


def header_repl(m):
    h = m.group(1).upper()
    if h in HEADER_NAMES:
        nm, t = HEADER_NAMES[h]
        return f'<field name="{nm}" type="{t}"/>'
    return m.group(0)


def name_repl(m):
    h = m.group(1).upper()
    n = name_dict.get(h)
    return f'name="{n}"' if n is not None else m.group(0)


total_resolved = 0
files_changed = 0
files_to_process = (
    [(CLASSES / f"{t}.binaryclass.xml") for t in TARGETS] if TARGETS
    else list(CLASSES.glob("*.binaryclass.xml"))
)
for p in files_to_process:
    if not p.exists():
        print(f"  MISS {p.name}"); continue
    text = p.read_text(encoding="utf-8")
    before = len(HASH_RE.findall(text))
    if before == 0: continue
    # Apply header pass first (preserves canonical type), then general resolution
    new = HEADER_RE.sub(header_repl, text)
    new = HASH_RE.sub(name_repl, new)
    after = len(HASH_RE.findall(new))
    if new != text:
        p.write_text(new, encoding="utf-8")
        files_changed += 1
        total_resolved += before - after
        if TARGETS or before - after > 5:
            print(f"  {p.name}: {before - after}/{before} resolved ({after} remain)")

print(f"\nTotal: {total_resolved} hashes resolved across {files_changed} files")
